version: "3"

services:
  map-it-api:
    depends_on:
      - map-it-database
    environment:
      - GOOGLE_ACTIONS_CLIENT_ID=${GOOGLE_ACTIONS_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./api/src:/usr/src/app/src
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    links:
     - map-it-database
  map-it-database:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: map-it,map-it-test
    volumes:
      - map-it-db-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  map-it-frontend:
    environment: 
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./src:/usr/src/app/src
      - ./static:/usr/src/app/static
      - ./build:/usr/src/app/build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090

volumes:
  map-it-db-data: