name: Build and test

on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: '10.16.0'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: develop
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: build and copy frontend
      run: |
        npm install
        npm run build
        # npm run test
    - name: npm install, build, and test backend
      run: |
        cd api
        npm install
        npm run build
        # TODO: setup test database
        # npm run test
