name: Run E2E tests
on:
  push:
    branches:
      - develop

env:
  NODE_ENV: e2e-test

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: docker-compose up
          wait-on: 'http://localhost:9090'
          wait-on-timeout: 300
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}