name: Deploy front-end

on:
  push:
    branches:
      - master
env:
  NODE_VERSION: '10.16.0'
  DIST_PATH: './dist'
  AZURE_STORAGE_ACCOUNT: mapitstorage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        # npm run test --if-present
    - name: 'Upload frontend to Azure blob storage'
      uses: Azure/github-actions/storage-blob-static-website@master
      env:
        AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
        PUBLIC_FOLDER: ${{ env.DIST_PATH }}
        SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
