name: Deploy to Azure

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: map-it-api
  AZURE_WEBAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '12.14.0'
  NODE_ENV: prod
  VAPID_KEYS_PUBLIC: ${{ secrets.VAPID_KEYS_PUBLIC }}
  API_HOST: ${{ secrets.API_HOST }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: build and copy frontend
      run: |
        npm config set unsafe-perm=true
        npm install
        npm run build
        cp -R dist/. api/public/
    - name: npm install and build backend
      run: |
        cd api
        npm config set unsafe-perm=true
        npm install
        npm run build
    - name: 'Deploy API to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
